apiVersion: v1
kind: Service
metadata:
  name: wiki
  namespace: wiki
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
  selector: 
    app: wiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-deployment
  namespace: wiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki
        image: phanoix/gcpedia@sha256:953ca552c0027be8f84174bfea511eea84afd0363b1063d88c81d26572508e6b
        ports:
        - containerPort: 80
        env:
        - name: "DOCKER"
          value: "1"
        - name: "DBHOST"
          value: "wiki-db"
        - name: "HOST"
          value: "wiki.gccollab.ca"
        - name: "PORT"
          value: ""
        - name: "OPENID"
          value: "true"
        readinessProbe:
          httpGet:
            path: /Main_Page
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /Main_Page
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.2"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        volumeMounts:
        - mountPath: /var/www/html/docker_gcpedia/images
          name: wiki-data-volume
        - mountPath: /var/www/html/docker_gcpedia/LocalSettings.php
          subPath: LocalSettings.php
          name: wiki-settings
      volumes:
      - name: wiki-data-volume
        persistentVolumeClaim:
          claimName: wiki-data-volume-claim
      - name: wiki-settings
        configMap:
          name: wiki-config
